default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: debug-statements
        exclude: ^todd/base/patches\.py$
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^tests/test_base/configs/diff\.html$
      - id: fix-encoding-pragma
        args:
          - --remove
      - id: forbid-submodules
      - id: mixed-line-ending
        args:
          - --fix=lf
        exclude: \.bat$
      - id: mixed-line-ending
        args:
          - --fix=crlf
        files: \.bat$
      - id: name-tests-test
        args:
          - --pytest-test-first
        exclude: ^tests/(helpers|.*/configs/.*\.py$|test_distillers/fgd/fgd.py$|test_losses/ckd/ckd.py$)
      - id: pretty-format-json
        args:
          - --autofix
        exclude: \.ipynb$
      - id: trailing-whitespace
        exclude: ^tests/test_base/configs/diff\.html$
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args:
          - -c
          - pyproject.toml
        additional_dependencies:
          - bandit[toml]
  - repo: https://github.com/PyCQA/doc8
    rev: v1.1.1
    hooks:
      - id: doc8
  - repo: https://github.com/pycqa/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-docstrings
          - mccabe
          - pep8-naming
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        additional_dependencies:
          - pydocstyle[toml]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          - -sn
  - repo: https://github.com/google/yapf
    rev: v0.40.0
    hooks:
      - id: yapf
        require_serial: true
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        exclude: docs
        additional_dependencies:
          - numpy
          - pandas-stubs
          - types-Pillow
          - types-toml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        exclude_types:
          - jupyter
        args:
          - tests
          - todd
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.6.0
    hooks:
      - id: commitizen
