repos:
- repo: git@github.com:pre-commit/pre-commit-hooks.git
  rev: v4.3.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-merge-conflict
  - id: check-yaml
  - id: debug-statements
    exclude: ^todd/base/_patches/builtins\.py$
  - id: end-of-file-fixer
    exclude: ^tests/test_base/test_configs/diff\.html$
  - id: fix-encoding-pragma
    args:
    - --remove
  - id: mixed-line-ending
    args:
    - --fix=lf
    exclude: \.bat$
  - id: mixed-line-ending
    args:
    - --fix=crlf
    files: \.bat$
  - id: requirements-txt-fixer
    files: requirements.txt|requirements/.*
  - id: trailing-whitespace
    exclude: ^tests/test_base/test_configs/diff\.html$
- repo: git@github.com:pycqa/flake8.git
  rev: 5.0.4
  hooks:
  - id: flake8
- repo: git@github.com:pycqa/isort.git
  rev: 5.10.1
  hooks:
  - id: isort
- repo: git@github.com:pycqa/docformatter.git
  rev: v1.5.0
  hooks:
  - id: docformatter
    args:
    - --in-place
# - repo: git@github.com:pycqa/pydocstyle.git
#   rev: 6.1.1
#   hooks:
#   - id: pydocstyle
- repo: git@github.com:pre-commit/mirrors-yapf.git
  rev: v0.32.0
  hooks:
  - id: yapf
    additional_dependencies:
    - toml
- repo: git@github.com:pre-commit/mirrors-mypy.git
  rev: v0.982
  hooks:
  - id: mypy
    exclude: docs
- repo: git@github.com:codespell-project/codespell.git
  rev: v2.2.1
  hooks:
  - id: codespell
    args:
    - todd
    - tests
- repo: git@github.com:commitizen-tools/commitizen.git
  rev: v2.35.0
  hooks:
  - id: commitizen
