default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
        exclude: ^todd/base/patches\.py$
      - id: end-of-file-fixer
        exclude: ^tests/test_base/configs/diff\.html$
      - id: fix-encoding-pragma
        args:
          - --remove
      - id: mixed-line-ending
        args:
          - --fix=lf
        exclude: \.bat$
      - id: mixed-line-ending
        args:
          - --fix=crlf
        files: \.bat$
      - id: trailing-whitespace
        exclude: ^tests/test_base/configs/diff\.html$
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
  # - repo: https://github.com/pycqa/pydocstyle
  #   rev: 6.1.1
  #   hooks:
  #   - id: pydocstyle
  - repo: https://github.com/pycqa/doc8
    rev: v1.1.1
    hooks:
      - id: doc8
  - repo: https://github.com/google/yapf
    rev: v0.40.0
    hooks:
      - id: yapf
        additional_dependencies:
          - toml
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        exclude: docs
        additional_dependencies:
          - numpy
          - types-Pillow
          - types-toml
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.5
    hooks:
      - id: codespell
        exclude_types:
          - jupyter
        args:
          - tests
          - todd
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.6.0
    hooks:
      - id: commitizen
