version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"
  jobs:
    post_install:
      - git install git+https://github.com/lvis-dataset/lvis-api.git@lvis_challenge_2021

sphinx:
  fail_on_warning: true

python:
  install:
    - path: .
      extra_requirements:
        - optional
        - doc
