name: Checkout TODD

description: Checkout TODD with LFS

inputs:
  lfs:
    description: If set to any value, checkout LFS files
    required: false

runs:
  using: composite
  steps:
    - uses: actions/checkout@master
    - run: git lfs ls-files --long | cut -d ' ' -f1 | sort > .lfs-assets-id
      if: inputs.lfs
      shell: bash
    - uses: actions/cache@v4
      if: inputs.lfs
      with:
        path: .git/lfs
        key: lfs-${{ hashFiles('.lfs-assets-id') }}-v1
    - run: git lfs pull
      if: inputs.lfs
      shell: bash
