name: build

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - python: 3.6
            torch: 1.8.0
            torchvision: 0.9.0
          - python: 3.8
            torch: 1.11.0
            torchvision: 0.12.0
    steps:
    - uses: actions/checkout@master
    - name: Create LFS file list
      shell: bash
      run: |
        git lfs ls-files --long | cut -d ' ' -f1 | sort > .lfs-assets-id
    - name: Restore LFS cache
      uses: actions/cache@v3
      id: lfs-cache
      with:
        path: .git/lfs
        key: lfs-${{ hashFiles('.lfs-assets-id') }}-v1
    - name: Git LFS Pull
      shell: bash
      run: git lfs pull
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==${{ matrix.torch }} torchvision==${{ matrix.torchvision }} -f https://download.pytorch.org/whl/torch_stable.html
        pip install -r requirements.txt
    - name: Run unittests
      run: |
        coverage run
    - name: Generate coverage report
      run: |
        coverage xml
        coverage report -m
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@master
