name: build

on:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
        include:
          - torch: "1.11.0"
            torchvision: "0.12.0"
            mmcv: "1.4.7"
    steps:
    - uses: actions/checkout@master
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==${{ matrix.torch }} torchvision==${{ matrix.torchvision }} -f https://download.pytorch.org/whl/torch_stable.html
        pip install mmcv==${{ matrix.mmcv }}
        pip install -r requirements.txt
    - name: Run unittests and generate coverage report
      run: |
        coverage run --branch --source mmdet -m pytest tests/
        coverage report -m
