name: publish

on:
  push:
    branches:
    - master

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.10"]
    steps:
    - uses: LutingWang/todd/.github/actions/checkout-todd@master
    - uses: actions/setup-python@master
      with:
        python-version: ${{ matrix.python }}
    - name: Build
      run: |
        python -m pip install build --user
        python -m build --sdist --wheel --outdir dist/ .
    - uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
    - uses: pypa/gh-action-pypi-publish@master
      if: startsWith(github.ref, 'refs/tags')
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
