name: publish

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11"]
    permissions:
      id-token: write
    steps:
      - uses: LutingWang/todd/.github/actions/checkout-todd@main
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python }}
      - name: Build
        run: |
          pip install build
          python -m build --sdist --wheel --outdir dist/ .
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: ${{ !startsWith(github.ref , 'refs/tags') }}
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
      - uses: pypa/gh-action-pypi-publish@release/v1
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
